name: budget
description: Application de gestion de budget personnel avec Firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  
  # State Management
  provider: ^6.1.1
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  fl_chart: ^0.66.0
  flutter_svg: ^2.1.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Ajoutez vos assets ici
  assets:
    - assets/images/logo-full.svg
    - assets/images/logo-icon.svg
    - assets/images/budget-pro-icon.svg
