name: budget
description: Application de gestion de budget personnel avec Firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  fl_chart: ^1.1.1
  flutter_svg: ^2.1.2
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.3.3
  url_launcher: ^6.2.0
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  shared_preferences: ^2.2.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  # Ajoutez vos assets ici
  assets:
    - assets/images/logo-full.svg
    - assets/images/logo-icon.svg
    - assets/images/logo-icon.png
    - assets/images/budget-pro-icon.svg
    - lib/l10n/app_en.arb
    - lib/l10n/app_fr.arb

flutter_launcher_icons:
  image_path: assets/images/logo-icon.png
  adaptive_icon_background: "#6C5CF7"
  adaptive_icon_foreground: assets/images/logo-icon.png
  android: true
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/logo-icon.png
    background_color: "#6C5CF7"
    theme_color: "#6C5CF7"
  windows:
    generate: true
    image_path: assets/images/logo-icon.png
  macos:
    generate: true
    image_path: assets/images/logo-icon.png

flutter_native_splash:
  color: "#F5F7FA"
  color_dark: "#0F172A"
  image: assets/images/logo-icon.png
  android: true
  ios: true
  web: true
  android_12:
    icon_background_color: "#F5F7FA"
    image: assets/images/logo-icon.png
